[package]
name = "sandbox"
version = "0.1.0"
authors = ["Jordan Rowland <36084892+Jordan-Rowland@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "0.9.1"